### ISSUE TITLE
API version in URL path?

### ISSUE THREAD

**Issue by toringe** [lonelycode/tyk#101]
I know the docs say that Tyk do not support api versioning in the path (api.hostname.com/service/v1/endpoint), but is there any plans on supporting this in future releases?

**Comment by lonelycode** [comment]
Yes there is (it's in our roadmap), the trick s trying to make it performant as it will most likely rely on a regex.

**Comment by JnMik** [comment]
Yeah we need this as well. 
I did a workaround like this for the moment, but i'm bypassing the Built-in versioning feature : http://screencast.com/t/aeGF3Frree6

**Comment by lonelycode** [comment]
This is now available in v1.8.3 and 0.9.6.3
