### ISSUE TITLE
Consul Service Discovery not working

### ISSUE THREAD

**Issue by geoand** [lonelycode/tyk#102]
Greetings,

I am trying to integrate Tyk with Consul for service discovery, but so far have been unsuccessful. 
Although I am an extreme golang newbie, I think the issues is that the code does not handle arrays being returned from the Consul API.

More specifically, the Consul API  for discovering the nodes that implement a specific service is documented [here](https://www.consul.io/docs/agent/http/catalog.html#catalog_service). As you can see the result is an array which Tyk doesn't seem to like.

Thanks, 
George

**Comment by lonelycode** [comment]
Yeah, our docs do state it needs to be a JSON object that gets traversed, not an array. It's a tricky one. Will investigate, we want to support default consul services.

**Comment by geoand** [comment]
Thanks for the update!
I'll check back soon :)

**Comment by lonelycode** [comment]
This is fixed 1.8.3 :-)

**Comment by geoand** [comment]
Awesome! Thanks!

**Comment by lonelycode** [comment]
Note on list-based returned values like Consul - you'll also need to also check the "Enable round-robin load balancing" option, otherwise you'll get errors. (you don't need to add any hosts though)

**Comment by geoand** [comment]
Thanks for the heads up!

I am updating the Docker Images and will check ASAP

**Comment by geoand** [comment]
Works like a charm!
Thanks once again!
