### ISSUE TITLE
Dependencies missing on startup causes failure rather than retries

### ISSUE THREAD

**Issue by richard-hulm** [lonelycode/tyk#103]
If the host manager (unsure about gateway/dashboard - will update if I see this again) can't find mongoDB on startup, it seems to crash.

If this could be improved for all 3 tyk components that would be great

N.B.
The only logs I got from the host-manager before it crashed is 

time="2015-09-08T15:24:54+01:00" level=info msg="Loading configuration" 
time="2015-09-08T15:24:54+01:00" level=info msg="Connecting to Redis" 
time="2015-09-08T15:24:54+01:00" level=info msg="Connecting to redis on: redis.service.consul:6379" 
time="2015-09-08T15:24:54+01:00" level=info msg="Connecting to Mongo"

So this is a fair amount of guesswork on my part!

Cheers,

**Comment by richard-hulm** [comment]
@lonelycode I can confirm the gateway and dashboard use the reconnect logic if mongo isn't avaliable at startup, but the host manager seems to consistently fail rather than retrying.

Is this something that is fairly easy to change?

**Comment by lonelycode** [comment]
Yes it should be, will add to roadmap for next version.

**Comment by lonelycode** [comment]
Host manager now reconnects on start if mongo is missing...
