### ISSUE TITLE
API Catalogue displaying swagger documentation  {{.HOST}} & {{.BASEPATH}} empty

### ISSUE THREAD

**Issue by adaouda** [lonelycode/tyk#105]
When using  dashboard 0.9.6.1 on an local machine to display  swagger documentation, i can't try it out because in the swagger template {{.host}} & {{.basepath}} are empty 

Doing the exact same thing on tyk cloud platform with the same software version, and it works.

Any idea ?

**Comment by lonelycode** [comment]
In your tyk_analytics.conf file, create a new field called 'hostname' and give it the hostname of your Tyk dashboard host and port (in our docker QuickStart we use Tyk.docker)
You will also need to set an organisation slug and an API slug
And, to get the routing to work (Tyk assumes that if hostname is set then routing will work), you'll probably need to get the host manager working. 
Finally, the template for the swagger docs is editable, so you can always edit the swagger init JS to suit your needs.
Then restart the dashboard. 
The portal does very little to try and work on a local host unless you are running our docker instances or something that has DNS and routing set up with the host manager.
There's too many ways of running Tyk for us to make it work universally, so we cover the most obvious cases and leave the rest up to the implementer.
Cheers,Martin



    _____________________________
