### ISSUE TITLE
Dashboard loosing sessions?

### ISSUE THREAD

**Issue by toringe** [lonelycode/tyk#109]
Using the current Dashboard 0.9.6.5. I keep getting "Not authorised" errors when navigating within the dashboard. If I reload the page when I get the error, I'm kicked out and need to login again, but if I just keep on clicking links, suddenly I'm authorized again.

There are no entries in the logs (output from tyk-analytics) that gives any indication of this issue. 

Btw: I'm using Chrome 45 on Ubuntu 14.04, and have purged the cache and cookies.

**Comment by lonelycode** [comment]
How odd. Login is cookie-based and matched with a redis key. 

Is your redis conection intermittent?

**Comment by lonelycode** [comment]
Also, does this happen in Firefox?

**Comment by toringe** [comment]
Found it! I had set `timeout 10` in the redis configuration, whilst my previous setups had disabled the timeout.
