### ISSUE TITLE
Inject user defined values in the request

### ISSUE THREAD

**Issue by yoanisgil** [lonelycode/tyk#111]
Hi,

I have this use case which I'd like to know if it is possible to implement with tyk:

I want to expose a third party API (whose access is controlled by mean of an API Key) through the Tyk Gateway. However I do not want users to be aware of the need for this API Key and thus let Tyk manage authentication/authorization in the usual way. However, since the API Key is mandatory there needs to be a way to associate this third party specific API Key with an user account and inject the value as a GET (or HTTP header parameter) for each request to the backend. 

Is this doable with Tyk?

Example:

Given user demo@example.com with third party API Key 10911109123baada1314
And endpoint /test
When I call http://gateway/test with authorizaton token for user demo@example.com
It should call http://backend/test?apikey=10911109123baada1314

The API Key value is unique to the user account. It could be seen as a custom attribute of the user account which could be injected in the request to be forwarded to the backend.

**Comment by lonelycode** [comment]
Does it need to be a query string parameter?

This is possible with headers - take a look at our header transforms: https://tyk.io/v1.8/api-management/transformations/ you can associate meta data (such as a hidden API key, with a token that you create. 

You can then access that token data from inside the header transform and body transform middleware as a variable namespace ($tyk_meta or _tyk_meta respectively)

If it has to be a querystring parameter you may need to resort to a custom JS middleware plugin that adds to the URL: 

https://tyk.io/v1.8/plugins/plugin-overview/

**Comment by yoanisgil** [comment]
Thanks @lonelycode ! I will take a t look and let you know. For now I have a use case where I need this transformation in a query string parameter but I do have another one which requires adding an Authorization header to the proxified request. I will keep in you the loop.

**Comment by yoanisgil** [comment]
@lonelycode  when I go here: 

https://tyk.io/v1.8/plugins/plugin-overview/

and click on [Tyk JavaScript API” section](https://tyk.io/v1.8/plugins/plugin-overview/plugins/jsvm-api) I get a page saying the **The page you are looking for cannot be found.**

**Comment by yoanisgil** [comment]
According to the definition documentation here:

https://tyk.io/v1.8/plugins/middleware-scripting/

a custom middleware must be added to the API definition but I am not sure how to do so given that I've created my API through the portal. Is it possible?

**Comment by yoanisgil** [comment]
Ok,

So I found out how to configure a middleware for an definition which has been stored in the mongo database. However I haven't an issue getting this custom middleware actually working, it looks like this:

```js

// ---- Sample middleware creation by end-user -----
var sampleMiddleware = new TykJS.TykMiddleware.NewMiddleware({});

sampleMiddleware.NewProcessRequest(function(request, session) {
    //log(JSON.stringify(request));
    //log(JSON.stringify(session.meta_data));
    //request.AddParams["api_key"] = session.meta_data['ho_apikey'];
    return sampleMiddleware.ReturnData(request, session.meta_data);
});

// Ensure init with a post-declaration log message
log("Sample middleware initialised");
```

but this yields an error:

```
time="2015-09-25T17:47:27Z" level=debug msg="SessionState: {0 59 60 60 0 3600 1445723247 3599 2520000 map[ff6a98aef61d4dfc41264b9ff0b01c0e:{HasOffers ff6a98aef61d4dfc41264b9ff0b01c0e [v1] []}] 56046649b12afc0001000001  {} false  false 5605511fb12afc0001000006 0 {[]} map[tyk_developer_id:56055845b12afc000100000e tyk_key_request_fields:map[] tyk_user_fields:map[]] [default]}" 
time="2015-09-25T17:47:27Z" level=debug msg="[STORE] SET Raw key is: 56046649b12afc0001000001f6e8f698124e4e267a6ea66fba80fa6b" 
time="2015-09-25T17:47:27Z" level=debug msg="No allowed URLS" 
time="2015-09-25T17:47:27Z" level=debug msg="Input key was: apikey-066031b5" 
time="2015-09-25T17:47:27Z" level=debug msg="[STORE] Setting key: apikey-066031b5" 
time="2015-09-25T17:47:27Z" level=debug msg="Rewriter started, stat was: " 
time="2015-09-25T17:47:27Z" level=debug msg="Input key was: apikey-066031b5" 
time="2015-09-25T17:47:27Z" level=error msg="Failed to decode middleware request data on return from VM: json: cannot unmarshal object into Go value of type string" 
time="2015-09-25T17:47:27Z" level=debug msg="{\"Request\":{\"AddParams\":{},\"Body\":\"\",\"DeleteHeaders\":[],\"DeleteParams\":[],\"Headers\":{},\"SetHeaders\":{},\"URL\":\"/ff6a98aef61d4dfc41264b9ff0b01c0e/\"},\"SessionMeta\":{\"tyk_developer_id\":\"56055845b12afc000100000e\",\"tyk_key_request_fields\":{},\"tyk_user_fields\":{}}}" 
```

any ideas?

**Comment by yoanisgil** [comment]
Turns out the issue was with this two metadata fields:

- tyk_key_request_fields":{}
- tyk_user_fields:{}

which are present by default ;) but they cannot be unmarshalled into JSON given that SessionMeta is a map[string]string:

https://github.com/lonelycode/tyk/blob/master/plugins.go#L31

**Comment by yoanisgil** [comment]
This is how I ended up implementing the middlewares:

https://gist.github.com/yoanisgil/869f131a3d5aa97816db
https://gist.github.com/yoanisgil/6f58179989303f21e1c1

Since I was using tyk with docker/compose I had to updated the API definition in mongodb:

```bash

$ docker exec -ti tykquickstart_tyk_mongo_1 /bin/bash

root@mongo:/# mongo
MongoDB shell version: 3.0.6
connecting to: test
Server has startup warnings: 
2015-09-25T20:55:58.640+0000 I CONTROL  [initandlisten] 
2015-09-25T20:55:58.640+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2015-09-25T20:55:58.640+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2015-09-25T20:55:58.640+0000 I CONTROL  [initandlisten] 
> use tyk_analytics;
switched to db tyk_analytics
> db.tyk_apis.update({"name": "Has Offers"}, {$set: {"custom_middleware":{"pre":[],"post":[{"name": "hasOffersMiddleware", "path": "middleware/hasoffers.js", "require_session": true}],"response":[]}}})
```

**Comment by lonelycode** [comment]
Nice one :-)
There's a way to enable middleware without modifying the mongo definition - it hasn't been documented yet, but essentially it involves creating a folder structure and dropping your middleware in:
- /etc/tyk---- middleware/-------- {API ID}/------------ pre/---------------- javascriptfile_with_session.js------------ post/---------------- javascriptfile_with_session.js
If you set your file up like this it will load the middleware for the api ids you set up, no messing with mongo needed.

**Comment by yoanisgil** [comment]
Yeah it was a bit of a pain but luckily the code was there so eventually I ended up figuring everything out. Can you send me a link to those lines of code explaining that undocumented behaviour. Once the files are in place do I need to restart Tyk? 

BTW once of the issues I had most trouble with was the fact that the name of the middleware needs to match the name of the variables in the JS file .... 

Bests,

Yoanis

**Comment by lonelycode** [comment]
The bit that loads the JS from a folder path is here:
https://github.com/lonelycode/tyk/blob/master/main.go#L254
Needs refactoring out into the plugins module.
