### ISSUE TITLE
Policy inheritance

### ISSUE THREAD

**Issue by toringe** [lonelycode/tyk#113]
Could it be an idea to have policies inherit from other policies?

**Comment by lonelycode** [comment]
Intriguing - do you have a sample use case?

**Comment by toringe** [comment]
No, it was just something that hit me. But on further reflection, the tight coupling between policies and specific access rights wouldn't make sense or at least make things more complex if policies were to inherit. So, never mind...

**Comment by toringe** [comment]
I'm closing this issue
