### ISSUE TITLE
Typo on front page

### ISSUE THREAD

**Issue by dave-kennedy** [lonelycode/tyk#121]
Under the "Policies and Tiers" heading:

    Enable tiered, metered access using powerfull key policies to apply to your developers

"powerfull" should be "powerful".

I would just submit a patch but it doesn't look like the front page is in this repo.

**Comment by lonelycode** [comment]
Hah! Yes we're working on putting all the copy into GH... I have sausage fingers so typos eventually find their way into the copy :-/

**Comment by lonelycode** [comment]
So we now have the content for the site in it's own repo: https://github.com/lonelycode/tyk-io-site-content
This doesn't include the home page though ;-)

**Comment by lonelycode** [comment]
Fixed typo on home page :-)
