### ISSUE TITLE
Do not send cleartext password when developers sign up

### ISSUE THREAD

**Issue by joshuajabbour** [lonelycode/tyk#125]
When developers sign up for the portal, their newly-created password is sent in cleartext in the "Your portal registration" email. This is really poor security, and I'd really like to feel that new developers who have access to my APIs can't have their accounts hijacked that easily.

**Comment by lonelycode** [comment]
In a hosted install you can update the portal email templates to exclude the password. We only include it in the release template because otherwise API owners wouldn't know it was available ;-)

In our cloud version - I see your point, we should probably change the template once we have a recovery feature :-/

**Comment by joshuajabbour** [comment]
Personally, I'd argue that there shouldn't even be a `password` template variable. Echoing back passwords is bad practice, and providing that facility to users leads to questions about other security decisions (in my opinion).  I mean, passwords should be a one-way transaction. Send it to the server (securely), then it's hashed and gone. (On that note, by "recovery" I hope you mean "reset".)

**Comment by azare** [comment]
I'm glad I saw this, I had seen where the apikey's are encrypted at rest and assumed passwords were one way encrypted too. I'm currently evaluating Tyk and if passwords are not encrypted unfortunately that's a deal breaker for us because of our security requirements. 

Please fix this!

**Comment by lonelycode** [comment]
Apologies, yes I did mean reset. 

I can see your reasoning in not having the password variable available to the template.

Not sure there's any need to cast aspersions on the wider security of the product, we appreciate the input, continually improve things, and take security very seriously.

@azare the passwords *are* encrypted in the database using bcrypt, they are only unencrypted for this single moment when this template is executed, the plaintext never reaches a storage medium. 

Take a look in the database, all the passwords that are stored are secure.

**Comment by lonelycode** [comment]
Password template field is now no longer accessible to portal owners. 

For those that can't wait until the next release, they can edit portal/email_templates/welcome.txt and portal/email_templates/welcome.html to remove the mention in their outbound emails (if they have the email integration enabled).

This change has been pushed to cloud.

**Comment by joshuajabbour** [comment]
I'm sorry, I did not mean to cast aspersions. I was trying to explain what goes through my mind when I receive my password via email; it does make me question security.

**Comment by lonelycode** [comment]
@joshuajabbour Completely understand, and agree with your assessment - which is why we pushed the change to the cloud version so quickly :-) This kind of feedback is important, and continually helps us improve quality.

**Comment by joshuajabbour** [comment]
:+1:

**Comment by azare** [comment]
@lonelycode Thanks for confirming that all passwords are encrypted at rest and only in clear form for that short during the initial registration.
