### ISSUE TITLE
Fix date ranges in dashboard

### ISSUE THREAD

**Issue by jaggerwang** [lonelycode/tyk#128]
![image](https://cloud.githubusercontent.com/assets/1255011/10861322/25ed9990-7fb6-11e5-883b-c9db9a408cdf.png)

**Comment by lonelycode** [comment]
Date ranges on first load are automatically computed in the dashboard, seems there's an off by one error there somewhere. 

It doesn't affect data retrieval as analytics data is time stamped with an ISO date object.

**Comment by lonelycode** [comment]
Fixed in develop.
