### ISSUE TITLE
Key not getting updated using Tyk dashboard

### ISSUE THREAD

**Issue by tandonraghav** [lonelycode/tyk#132]
I installed tyk and tyk dashboard and everything seems to be working fine, as I am able to use tyk as a proxy and also create keys. However, when I try to modify the key using the Dashboard it says  <b>Error
Key object validation failed.</b>. Can you please let me know what is happening.<br>
Note: I am able to perform CRUD key operation using tyk REST directly.

**Comment by lonelycode** [comment]
You might jsut need to add a meta_data key to your session object (either via the REST API or add some meta data using the dashboard) - there's JSON Schema validation error sometimes when a key is created without meta_data in the gateway and is then managed in the dashboard.

We'll be addressing this in the next version.

**Comment by tandonraghav** [comment]
Thanks..Yeah adding meta data solved the issue.
