### ISSUE TITLE
Api Versioning using Paths

### ISSUE THREAD

**Issue by tandonraghav** [lonelycode/tyk#133]
I am able to use Header and Url param for Version Management, but I want to do version based on Paths. I see in the Docs that Path versioning is not supported in tyk.
But then Dashboard displays a First Url Element option, can you please tell how can i use it.
I want to version like /v1/*

**Comment by lonelycode** [comment]
The docs are a bit out of date. Will leave this ticket open as a reminder to update them.

Select the dashboard option, set a tag to match for the version and use it as part of your URL structure.

Any paths you specify operations on must include the version though.

**Comment by tandonraghav** [comment]
Thanks for your quick reply.
Can you please elaborate like if I want to use /v1/** then where do I need to put the tag for this?
I tried using advanced Option but that is not working.

**Comment by lonelycode** [comment]
its the same as using the Param based and header based version, you set this as the type and then in the list of versions under the setting you add your various version tags and expiry dates.

The tag should just be v1 for /v1/ based URLs etc.

**Comment by tandonraghav** [comment]
Sorry but still it is not working.

Target Url- http://localhost:8080/test-v1/v1/accounts/
Listen Path- /v1/test/accounts/

Version Management:-
Key Name- v1

Advanced Options:-
Tags - v1 (Added this tag for this API)

Then I am hitting the Url as :- http://localhost/v1/test/accounts/{id}

Response is:-
{
error: "Version information not found"
}

**Comment by lonelycode** [comment]
Why is it in your listen path? The listen path should be a single, unique path that precedes any API specific info.

Listen on: /API-name/
Version tag: v1
Target: http://API.your domain.com/

Then direct traffic to 
Tyk.domain.com/listen_path/verion-tag/resource

**Comment by tandonraghav** [comment]
Thanks...worked this way!!!

**Comment by tandonraghav** [comment]
Hello,
I am having issue with <b>'strip_listen_path'.</b> I want listen_path to be as part of upstream request. How can i modify this parameter from dashboad. I modified directly in Mongo but again updating from dashboard is setting back to true.

This is causing issue with Versioning as Api version shows some wierd versionsing as <b>"http:".</b>
Setup details:-

Rest Service Url- localhost:8080/API-name/v1/resource

Apache Http Server:-(localhost)
Proxy /    tyk:port
Tyk Setup:-
Target Url:- http://localhost:8080/
ListenPath /API-name/
Version tag : - v1(First URL param)

Now I am hitting localhost/listen_path/v1/resource
But the API-name is not in the upstream request and the url is only /v1/resource

Overall design is 
Apache HTTP server-> Tyk - > Apache Http Server (used to rooute to different tomcat based on version)-> Tomcat
