### ISSUE TITLE
To modify "strip_listen_path" from Dashboard

### ISSUE THREAD

**Issue by tandonraghav** [lonelycode/tyk#134]
Hello,
I am having issue with 'strip_listen_path'. I want listen_path to be as part of upstream request. How can i modify this parameter from dashboad. I modified directly in Mongo but again updating from dashboard is setting back to true.

This is causing issue with Versioning as Api version shows some wierd versionsing as "http:".
Setup details:-

Rest Service Url- localhost:8080/API-name/v1/resource

Apache Http Server:-(localhost)
Proxy / tyk:port
Tyk Setup:-
Target Url:- http://localhost:8080/
ListenPath /API-name/
Version tag : - v1(First URL param)

Now I am hitting localhost/listen_path/v1/resource
But the API-name is not in the upstream request and the url is only /v1/resource

Overall design is 
Apache HTTP server-> Tyk - > Apache Http Server (used to rooute to different tomcat based on version)-> Tomcat

**Comment by lonelycode** [comment]
There's an issue with path-based versioning where the analytics aren't recorded properly. It has been fixed in develop so will be fine in the next version.

As for modiying listen path - just change it in the tyk_analytics.conf file:
```
{
...
    "hide_listen_path": false,
...
}
```

Then restart the dashboard, it should be editable (might need to refresh browser)

**Comment by tandonraghav** [comment]
When is the next version release?

**Comment by lonelycode** [comment]
When it is ready ;-)

**Comment by tandonraghav** [comment]
Really cool..but we are planning to deploy it in production, so need to
know.☺

**Comment by lonelycode** [comment]
I'd suggest not using the path-based versioning then - we have no release date that we can publish. It's close though.

**Comment by tandonraghav** [comment]
Ok..thanks...

**Comment by lonelycode** [comment]
Not with the dashboard. If you modify it in the DB, then save the API in the dashboard, it will overwrite the setting.

This is not causing the issue with the analytics, that is a bug. When tyk writes the analytics it doesn't grab the version data properly if it's a path-based version.

Tip: Don;t version your API and just have it as it's own API, then set the listen path to api/

Users will access api/v1/* and v1/* will be passed on to your app.

If you want more control, add a rewrite rule in apache to detect requests to v1/ and rewrite them to listen_path/v1 then you can have it sit on root.

**Comment by tandonraghav** [comment]
ok...rather than doing this in Apache I can use <b>target url</b> to include listen_path also. Will there be any issue if i use target url as http://localhost:8080/API-name and listen_path as /API-name.
Just want to confirm that this approach is fine?

**Comment by lonelycode** [comment]
Yeah that would be fine - you may need to fiddle about with slashes though, so target:

http://localhost:8080/API-name/

Then listen:

/API-name/

That's how we usually do it. This will cause Tyk to listen on http://domain.com/API-name, then strip "API-name" and take the rest of the url and put it on the end of target_url, so you get it back on the other end.

**Comment by tandonraghav** [comment]
Yeah thats what I am doing, everything is working fine if I place listen_path in target url.
Thanks for clarifying all my doubts and for your time.

**Comment by tandonraghav** [comment]
I am closing this issue. If you can give the option of "strip_listen_path":true/false through dashboard that will be good.

**Comment by lonelycode** [comment]
had a dig around in this issue, to fix, you can set it so that you can enable strip_listen_path by setting force_api_defaults to false in analytics.conf - the dashboard will still override the setting if you save it, but the API will not.

**Comment by tandonraghav** [comment]
I didnt got ur comment. I changed the force_api_defults:false in tyk_analytics, but then too it is setting "strip_listen_path" : true, Can you please explain a bit more.
