### ISSUE TITLE
Defining multiple endpoints in an app definition

### ISSUE THREAD

**Issue by patrickmslatteryvt** [lonelycode/tyk#17]
Is is possible to define more than one target_url endpoint per app definition?
For instance assume we have three web servers hosting the endpoint app, could I define the endpoints something like this:

    "proxy": {
        "listen_path": "/api/",
        "target_url": "http://192.168.0.10/",
        "target_url": "http://192.168.0.20/",
        "target_url": "http://192.168.0.30/",
        "strip_listen_path": true
    }

Or would it be better to just have a pool defined that round-robins the requests to the endpoints?

**Comment by lonelycode** [comment]
Fixed in master - you can now round-robin load balance to multiple upstream services using 

```
	...
	"enable_load_balancing": true,
	"target_list": [
		"http://server1", 
		"http://server2", 
		"http://server3"
	],
```

In the `proxy` section of the API Definition
