### ISSUE TITLE
Log to file

### ISSUE THREAD

**Issue by kevyau** [lonelycode/tyk#31]
Is it possible to output logs to file ?

**Comment by lonelycode** [comment]
If you are running on a *nix system you could just direct the output of the application to logs, this command would put both stdout and stderr to an output file:

    $> ./tyk  >> tyk.log 2>&1  

We tend to install the tyk processes using [supervisord](http://supervisord.org/), which automatically handles logging stdout and stderr to file into `/tmp` and also manages log rotation, great little utility for managing start-up processes. Tyk (and golang apps in general) don't play well with daemonizing, so supervisord is ideal to manage them and takes care of log management to boot :-)
