### ISSUE TITLE
User with username for Basic Auth can not be created

### ISSUE THREAD

**Issue by camann9** [lonelycode/tyk#34]
A user with basic auth settings can not be created because it raises an non-descript error. See http://i.imgur.com/FtPbugV.png . I can only create a user without basic auth and add the password in edit mode. But then I can not set the user name any more. This means I have to either use the generated hash or rename the apikey in redis.

**Comment by lonelycode** [comment]
This is a bug, though only in the dashboard. Nice find, the angular app is actually using the incorrect dashboard API endpoint:

Request URL: `//api/keys/basic/{{username}}`

It should be using the new API-based structure: `/apis/:apiId/keys/basic/:username`

**Comment by lonelycode** [comment]
Also fixed in dev.
