### ISSUE TITLE
Endpoint name in analytics incorrect

### ISSUE THREAD

**Issue by camann9** [lonelycode/tyk#38]
Hi, my analytics look like this: http://i.imgur.com/bSMyytL.png . The thing is that I didn't define any endpoint named /
The only endpoint I created is called /test, see here: http://i.imgur.com/1FIrAUw.png .

**Comment by lonelycode** [comment]
The analytics are correct, the dashboard sets up API endpoints to strip the path upstream, so you create an endpoint for /test/, then access /test/widgets and tyk will strip /test/ from the endpoint so it doesn't get proxied, if your upstream proxy is http://camann9.com/api, then without this option turned on, Tyk would proxy to http://camann9.com/api/test/widgets, with the option it proxies to http://camann9.com/api/widgets

If you look at the drop-down in the dashboard, you will be able to filter your API results by API:

![API Choices](http://i.imgur.com/edCeyaU.png)

**Comment by camann9** [comment]
Ok, thanks. Sorry to bother you.

**Comment by lonelycode** [comment]
No worries :-) This is all going to need to be put in the docs, which are in need of updating asap.
