### ISSUE TITLE
Use encryption for basic auth password in database

### ISSUE THREAD

**Issue by camann9** [lonelycode/tyk#39]
Currently the password for basic auth is stored in clear text in the redis datastore. Users might use the same password for other websites. Thus a compromised redis store would mean that all passwords of users are known to an attacker which might lead to hacked email accounts, etc. Preserving backward compatibility with existing data in the DB is not hard, just add a field "pwencoding" that stores the hash algorithm used and defaults no 'none' if it's not present.
Tyk analytics already uses password hashing but I don't know which one. Using PBKDF would probably be a good idea.

**Comment by lonelycode** [comment]
Tyk analytics uses bcrypt.

**Comment by lonelycode** [comment]
Basic Auth passwords are now hashed by default in the development branch of Tyk, will be in the next point release.
