### ISSUE TITLE
access granularity

### ISSUE THREAD

**Issue by thorstenz** [lonelycode/tyk#41]
It is my understanding that the API access management
does not differentiate the access type. 

It would be great to have something like this:
(taken from https://tyk.io/v1.4/rest-api/api-key-management/ )
{
    "allowance": 999,
    "rate": 1000,
    "per": 60,
    "expires": 0,
    "quota_max": -1,
    "quota_renews": 1406121006,
    "quota_remaining": 0,
    "quota_renewal_rate": 60,
    "access_rights": {
        "234a71b4c2274e5a57610fe48cdedf40": {
            "api_name": "Versioned API",
            "api_id": "234a71b4c2274e5a57610fe48cdedf40",
 
           --> extra part
            "api_access_type": [ "GET", "PUT", "POST" ]
            or
            "api_access_type": [ "GET" ]
            <-- end of extra part

            "versions": [
                "v1"
            ]
        }
    },
    "org_id": "53ac07777cbb8c2d53000002"
}

The api_access_type would list the allowed REST access types. 
With this additional feature one can create an access key with limited or enhanced rights.

**Comment by lonelycode** [comment]
This is fixed in master - see the changelog for details, implementation is a white list URL regex + Method check. Allows for highly granular policies to be created.
