### ISSUE TITLE
nginx rewrite issues

### ISSUE THREAD

**Issue by kudigaracoder** [lonelycode/tyk#45]
Hi,
We've followed your installation & setup guide to install the gateway & the dashboard. We've independently verified the data from mongodb & they seem to be fine. When we hit up the URL, nginx always seems to respond back with 'Bad Gateway' (or) 'Internal Server Error'.
Our sites-available config for tyke is below

```
server {
    listen 5000;
    server_name <our_server_name>;

    gzip              on;
    gzip_buffers      16 8k;
    gzip_comp_level   4;
    gzip_http_version 1.1;
    gzip_min_length   1280;
    gzip_types        text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript image/x-icon image/bmp;
    gzip_vary         on;

    # The Go application server
    location / {
        rewrite /(.*) /API_LISTEN_PATH/$1 break;

        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass http://tyk;
    }
}
```
Our assumption is that the API_LISTEN_PATH is not being picked up from mongodb. How can I resolve this?

**Comment by lonelycode** [comment]
Hi,

Does the tyk installation work without NGinX on the raw listen path?

If NGinX is giving a bad gateway error then it can't connect to Tyk at all, which means the node either isn't running or the port is misconfigured. If tyk couldn't find he listen path, it would respond with a 404.

Can you see the Tyk node log output? Would suggest first verifying that tyk is listening, that the raw tyk URL works and responds, and then NGinX.

Cheers,
Martin

**Comment by kudigaracoder** [comment]
Thanks Martin, We've managed to resolve the conflicts & got the redirects working (directly through tyke port, nginx rewrite is still throwing a 404).
One other thing we've noticed is that the configuration update through the Analytics dashboard doesn't seem to reflect real-time. It works only when we restart tyke every time. Are there specific cache settings we should be looking at?

**Comment by lonelycode** [comment]
Hi,

You will need to use the host manager that comes with the dashboard tarbal to auto-reload the configuration from the dashboard. Or you can use the REST API (hot reload).

Thanks,
Martin

**Comment by kudigaracoder** [comment]
ITS ALIVE~
Thanks a lot Martin!
