### ISSUE TITLE
Custom SSL Certificate at the Target Endpoint

### ISSUE THREAD

**Issue by kruffin** [lonelycode/tyk#46]
Would be great to be able to disable SSL certificate validation on a per endpoint basis or the capability to import self-signed certificates that are trusted just not signed by a trusted authority (equivalent of a Java keystore). The former more appropriate for development, while the latter is more appropriate for production B2B scenarios where there isn't a need for a third party to establish trust.

**Comment by lonelycode** [comment]
There may be a workaround for this: https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/tyk-community-support/-KD2L8M6qh0
