### ISSUE TITLE
Host manager does not reconnect to Redis

### ISSUE THREAD

**Issue by megatomz** [lonelycode/tyk#51]
At the moment if host manager's connection to Redis is interrupted (e.g. Redis cluster failover occurred) the host manager process dies. Ideally it would attempt to re-try connection a 
(configurable?) number of times before giving up.

More details on the issue that caused this issue to be raised can be found at: https://groups.google.com/forum/#!topic/tyk-community-support/M6YAB5IC248

**Comment by lonelycode** [comment]
Fixed in 1.6
