### ISSUE TITLE
go-uuid not available anymore

### ISSUE THREAD

**Issue by mDomingues** [lonelycode/tyk#53]
Hi,

When trying make 'build/container' it failed due missing data for go-uuid. 
I can't add it to GOPATH this way and therefore, I can't build the container to run the app. 

https://code.google.com/p/go-uuid/uuid

Any solution for this ?

**Comment by lonelycode** [comment]
This is resolved in master branch, all dependencies for google code were removed ages ago. 

I assume you are building from a release, if so you'll need replace all the dependencies references, we pinned go-uuid to this repo:

"github.com/lonelycode/go-uuid/uuid"

Thanks google code for breaking our backwards compatability :-(

**Comment by mDomingues** [comment]
So how do you explain this, master branch up-to-date:

>> make build/container
GOOS=linux GOARCH=amd64 go build -o build/tyk
../../gocode/src/github.com/lonelycode/osin/tokengen.go:7:2: cannot find package "code.google.com/p/go-uuid/uuid" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/code.google.com/p/go-uuid/uuid (from $GOROOT)
	/Users/xxxxx/gocode/src/code.google.com/p/go-uuid/uuid (from $GOPATH)
analytics.go:8:2: cannot find package "labix.org/v2/mgo" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/labix.org/v2/mgo (from $GOROOT)
	/Users/xxxxx/gocode/src/labix.org/v2/mgo (from $GOPATH)
../../gocode/src/github.com/lonelycode/tykcommon/api_defintitions.go:6:2: cannot find package "labix.org/v2/mgo/bson" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/labix.org/v2/mgo/bson (from $GOROOT)
	/Users/xxxxx/gocode/src/labix.org/v2/mgo/bson (from $GOPATH)
make: *** [build/tyk] Error 1

**Comment by lonelycode** [comment]
Dammit, a dependency in a pinned dependency... missed that one. Try it now (you'll need to git update the osin lib)

**Comment by mDomingues** [comment]
Ok, did it and now complains on this:

go build runtime: linux/amd64 must be bootstrapped using make.bash
make: *** [build/tyk] Error 1

**Comment by lonelycode** [comment]
The makefile is set up to compile for linux on amd64, if you are running on a different platform you'll need to modify this line:

`GOOS=linux GOARCH=amd64 go build -o build/tyk`

in the Makefile to be whatever platform you are building for, according to the golang docs you have the following to pick from

$GOOS	$GOARCH
darwin	386
darwin	amd64
dragonfly	386
dragonfly	amd64
freebsd	386
freebsd	amd64
freebsd	arm
linux	386
linux	amd64
linux	arm
netbsd	386
netbsd	amd64
netbsd	arm
openbsd	386
openbsd	amd64
plan9	386
plan9	amd64
solaris	amd64
windows	386
windows	amd64

FYI: The reason this isn't working is because we don't actively support Docker yet, this file was supplied by a third-party, so it's pretty custom to their setup.

**Comment by mDomingues** [comment]
Your totally right!! I did it using other way but thanks for that information.
I recompiled go for all distributions available: brew reinstall go --cross-compile-all
This way user doesn't need to change the docker file to the OS based version.

Now that I have the server up and running, what's the endpoint for the dashboard and management ? I saw a few endpoints in main but nothing as I was expecting..

**Comment by lonelycode** [comment]
haha, wow - that's a bit much, it may just be a case of building for whatever is on the system, I don;t think you need to set those flags per se. 

There's quite a lot you are missing i think - the dashboard is a seperate component, that docker file is just for the gateway binary. 

Would suggest looking at the docs as there's quite a lot!

https://tyk.io/v1.5/setup/install-dashboard/

Thanks,
Martin

**Comment by mDomingues** [comment]
Ok ok! Many thanks for your help! :)
