### ISSUE TITLE
Return API access key when a user is created using the admin API

### ISSUE THREAD

**Issue by mevcloud** [lonelycode/tyk#56]
When you create a user with the admin API (/admin/users) it would be useful to get the api access key back, so you can then proceed and modify it using the users API. 
If that information is not returned in the response we can end up in deadlock situations as the one described here

https://groups.google.com/forum/#!msg/tyk-community-support/dNT3Mymyu0A/WCn2QxtBwj8J

**Comment by lonelycode** [comment]
This should be fixed in the latest dashbaord release (see the 1.6 release section for 0.9.4.1)
