### ISSUE TITLE
Dashboard 0.9.4 doesn't work in Safari

### ISSUE THREAD

**Issue by avart** [lonelycode/tyk#57]
Hi,

We recently upgraded to Tyk 1.6 and the 0.9.4 dashboard. I made a new docker container which connects to the same database I've been using for Tyk 1.5, but when I log in to the dashboard with Safari, I only see the leftmost column, but nothing in the "main" field of the dashboard, as seen in the attached screenshot.
Firefox and Chrome works fine.

I've cleared all browser cache and tried with two versions of Safari, and I see the same behaviour.

I'm running Tyk and the dashboard from a custom Docker container, a version of which you can find here:
https://github.com/avart/docker-tyk

![screen shot 2015-05-04 at 09 55 08](https://cloud.githubusercontent.com/assets/967024/7453725/a602137c-f26c-11e4-8710-45036908af47.png)

**Comment by lonelycode** [comment]
This should be resolved now - you'll need to pull the latest docker images though.
