### ISSUE TITLE
Incorrect Content Type in Advanced Management API

### ISSUE THREAD

**Issue by lyptt** [lonelycode/tyk#63]
I seem to be getting ```Content-Type text/plain``` in my responses when sending requests to the management API instead of ```application/json```.

I'm definitely sending ```application/json``` in my requests. Is this an oversight or is there anything special I need to do to get back a valid content type?

**Comment by lonelycode** [comment]
It's a bug, will add to fix list - thanks for pointing it out :-)

**Comment by richard-hulm** [comment]
Just to ensure you're aware, the gateway API also has this issue on a couple of endpoints, so far I've spotted it on the organisations

**Comment by lonelycode** [comment]
@richard-hulm Which version are you running of the gateway? We added a global response code fto the Tyk gateway API in September last year?

Are you suer you aren;t talking about the Avanced API?

**Comment by richard-hulm** [comment]
Not entirely sure of the distinction I'm afraid, I know it's part of the gateway binary at least.

The endpoint I'm hitting is localhost:3000/admin/organisations/ and getting a text/plain; charset=utf-8 header back even if I specify application/json

/admin/users/ also seems to give the same thing when I'm creating an admin user

**Comment by lonelycode** [comment]
Ah, that's actually in the dashboard - have just pushed a fix to our main branch, will be resolved int he next release...
