### ISSUE TITLE
Impossible to set slug and name when creating an Organization in Advanced Management API

### ISSUE THREAD

**Issue by lyptt** [lonelycode/tyk#66]
Given a HTTP request like this:

```
POST http://dashboard.local/admin/organisations/
admin-auth: 12345
Content-Type: application/json

{
    "owner_name": "My Org",
    "owner_slug": "myorg"
}
```

The resulting object stored in the database does not contain the name or slug specified:

```json
{
  "_id": {
    "$oid": "555b07526cf82c03af000003"
  },
  "owner_name": "",
  "owner_slug": "",
  "apis": [],
  "key_quota": 0
}
```

I've matched the organization objects mentioned in the documentation for the get requests, do POST/PUT use different key names? Neither creation nor update seems to set these fields.

**Comment by lonelycode** [comment]
Which dashbaord release are you using? 0.9.4.4?

**Comment by lonelycode** [comment]
This is how our script does it via the command line:

`curl --silent --header "admin-auth: 12345" --header "Content-Type:application/json" --data '{"owner_name": "TestOrg5 Ltd.","owner_slug": "testorg"}' http://$LOCALIP:3000/admin/organisations`

**Comment by lyptt** [comment]
It looks like we're currently on 0.9.4.1. I'll try upgrading and see if that helps

**Comment by lyptt** [comment]
The docker script -does- work in importing the organization which is the odd thing, I'm unsure of what we're doing differently unless it's just that the docker script pulls in a newer dashboard

**Comment by lonelycode** [comment]
Ah 0.9.4.1 had an old schema for the organisations object that excluded those fields, the quickstart uses the latest docker container so I would recommend moving to 0.9.4.4

**Comment by lyptt** [comment]
Brilliant, that's fixed it. Thanks!
