### ISSUE TITLE
Advanced Management API - Associate api definition to organization

### ISSUE THREAD

**Issue by lyptt** [lonelycode/tyk#67]
Currently when creating new API definitions using the Advanced Management API, the org_id field is ignored, although it is returned from a GET request. It would be nice if it was possible to associate a definition with a given organization.

Currently the workaround is to create API definitions with an access token from a user that belongs to that organization. This might get a tad complicated when managing multiple organizations however.

**Comment by lonelycode** [comment]
You can do this if you create a super user with the API (I think), create a new user which has no OrgID assigned using the admin/users endpoint.

Then use this to create new APIs, when it creates the API it will have an empty OrgID, but if you then do a PUT update with the OrgID you want it *should* stick.

This is intentional, we do not want user tokens from other organisations being able to create API's that do not belong to the org. Having a single super user (no organisation affilliation) then gives cross-org read access and some write capability.

**Comment by lyptt** [comment]
Yeah that's exactly what we were doing, we had a super user with no organization and then created API definitions with it. The lack of an org id was the main reason this was problematic.

When going with your suggested workflow I now get a stack dump on the Dashboard process.

For the following request:

```
PUT http://dashboard.local/api/apis/a7958b937a44438954ad16d11c2c9e14

Authorization: 038bd0544e3149eb7323e58248521d7a
Content-Type: application/json

{
    "api_definition": {
       "org_id":"555b31436cf82c26b2000006"
    }
}
```

I get the following error in the console:

```
ERROR 2015/05/19 12:53:16.996029 panic_handler.go:26: PANIC
URL: /api/apis/a7958b937a44438954ad16d11c2c9e14
ERROR: Invalid input to ObjectIdHex: "a7958b937a44438954ad16d11c2c9e14"
STACK:
goroutine 33 [running]:
github.com/gocraft/web.(*Router).handlePanic(0xc208062160, 0xc20802c240, 0xc20802c260, 0x814a80, 0xc20808c820)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:251 +0x37a
github.com/gocraft/web.func·001()
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:43 +0x84
labix.org/v2/mgo/bson.ObjectIdHex(0xc2080c510e, 0x20, 0x0, 0x0)
	/home/tyk/go/src/labix.org/v2/mgo/bson/bson.go:174 +0x207
main.(*ApiDefinition).GetApiByInternalId(0xc208061400, 0xce6f68, 0x0, 0xc2080c510e, 0x20, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk-analytics/ModelApiDefintion.go:71 +0x17a
main.(*APIContext).UpdateApiDetail(0xc208038a50, 0x7fb119c90e90, 0xc20802c240, 0xc20802c260)
	/home/tyk/go/src/github.com/lonelycode/tyk-analytics/ApiApiManagement.go:265 +0x449
reflect.Value.call(0x876d00, 0xa9ad80, 0x13, 0x973470, 0x4, 0xc20810c908, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x876d00, 0xa9ad80, 0x13, 0xc20810c908, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/gocraft/web.func·002(0x7fb119c90e90, 0xc20802c240, 0xc20802c260)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:113 +0xbc0
main.(*APIContext).ApiAuthorisationRequired(0xc208038a50, 0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/lonelycode/tyk-analytics/Main.go:327 +0x11d
reflect.Value.call(0x8a0d80, 0xa9ab80, 0x13, 0x973470, 0x4, 0xc20810ce18, 0x4, 0x4, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x8a0d80, 0xa9ab80, 0x13, 0xc20810ce18, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/gocraft/web.(*middlewareHandler).invoke(0xc20808f470, 0x96e0e0, 0xc208038a50, 0x16, 0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:133 +0x2d5
github.com/gocraft/web.func·002(0x7fb119c90e90, 0xc20802c240, 0xc20802c260)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.func·004(0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/static_middleware.go:23 +0x64a
github.com/gocraft/web.(*middlewareHandler).invoke(0xc2080b9bc0, 0x937c80, 0xc208038a40, 0x16, 0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x71
github.com/gocraft/web.func·002(0x7fb119c90e90, 0xc20802c240, 0xc20802c260)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.func·004(0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/static_middleware.go:23 +0x64a
github.com/gocraft/web.(*middlewareHandler).invoke(0xc2080b9b60, 0x937c80, 0xc208038a40, 0x16, 0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x71
github.com/gocraft/web.func·002(0x7fb119c90e90, 0xc20802c240, 0xc20802c260)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.LoggerMiddleware(0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/logger_middleware.go:16 +0x78
github.com/gocraft/web.(*middlewareHandler).invoke(0xc2080b9b30, 0x937c80, 0xc208038a40, 0x16, 0x7fb119c90e90, 0xc20802c240, 0xc20802c260, 0xc20808c530)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:131 +0x71
github.com/gocraft/web.func·002(0x7fb119c90e90, 0xc20802c240, 0xc20802c260)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.(*Router).ServeHTTP(0xc208062160, 0x7fb119c90e58, 0xc2080306e0, 0xc2080c2820)
	/home/tyk/go/src/github.com/gocraft/web/router_serve.go:48 +0x3cf
net/http.serverHandler.ServeHTTP(0xc20805cb40, 0x7fb119c90e58, 0xc2080306e0, 0xc2080c2820)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208030640)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.
```

**Comment by lyptt** [comment]
I'm unsure if I need to have the entire definition sent again just to update the organization ID, obviously this is a PUT not a PATCH so I probably do need to, but this seems like a lot of effort to go to just to update one field.

**Comment by lonelycode** [comment]
Ah, you are using the api_id, not the object ID - they are different, one is a universal representation and the other is an internal database ID, the Advanced API will need the ObjectID, not the api_id.

You need to re-send the whole object.

I would suggest Creating the Org, GET it again, modify the OrgID then PUT it.

**Comment by lyptt** [comment]
Ah okay, that makes a bit more sense. I should be able to use the ID returned in the Meta field when creating the initial definition for that then.

It would be nice if there was a way of doing this that didn't require sending over the definition twice. Either by adding a PATCH operation so the field can be updated there without updating anything else, or by adding support for reading the field in the POST request, simply to just make the API a bit easier to work with.

**Comment by lonelycode** [comment]
There's a lot of security cruft sitting on top of this that prevents users from being able to manipulate objects outside of their organisation.

Agree that having more methods would make this particular workflow easier, but the thing is this would work with a single request if you used a user token that part of the organisation.

We currently do something like this for organisation-level operations:

1. Create a temporary user for the org, get their auth-code (you dont need a password, jsut ther eturned auth token)
2. Manipulate objects
3. Delete the temporary user with their own token

Much easier, and (1) and (3) are pretty much template code that just ened an org ID.

**Comment by lyptt** [comment]
Yeah, and that gets back to what our workaround involves whereby you create your definitions using an access token from a user associated to that organization. It seems like this is the official way you're supposed to go about this, so we'll continue with that method for the time being.
