### ISSUE TITLE
tyk-dashboard runtime error.

### ISSUE THREAD

**Issue by samek** [lonelycode/tyk#68]
Hi, 

Currently We have (not in production) 2 tyk gw servers. 

When I try to use tok-dashboard I get: 

----------------------------------------------------------------------------------------------------------------------------------------
URL: /api/users
ERROR: runtime error: invalid memory address or nil pointer dereference
STACK:
goroutine 12 [running]:
github.com/gocraft/web.(*Router).handlePanic(0xc20807c160, 0xc208640000, 0xc208640020, 0x851e00, 0xc20800a060)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:251 +0x37a
github.com/gocraft/web.func·001()
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:43 +0x84
main.(*ApiModel).IsJsonValid(0xc20805b5f0, 0xc20805d560, 0x54, 0x45ea63, 0x0, 0x0, 0x0)
	/home/martin/code/go/src/github.com/lonelycode/tyk-analytics/ApiAdminMethods.go:35 +0x496
main.(*APIContext).ValidateUserObject(0xc208038a38, 0xc20805d560, 0x54, 0x7fb0146bfc68, 0xc208640000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/martin/code/go/src/github.com/lonelycode/tyk-analytics/ApiUsers.go:96 +0xb4
main.(*APIContext).CreateUser(0xc208038a38, 0x7fb0146bfc68, 0xc208640000, 0xc208640020)
	/home/martin/code/go/src/github.com/lonelycode/tyk-analytics/ApiUsers.go:120 +0x3d9
reflect.Value.call(0x7ef2a0, 0x9d9e00, 0x13, 0x8d2c00, 0x4, 0xc208300d00, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x7ef2a0, 0x9d9e00, 0x13, 0xc208300d00, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/gocraft/web.func·002(0x7fb0146bfc68, 0xc208640000, 0xc208640020)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:113 +0xbc0
main.(*APIContext).ApiAuthorisationRequired(0xc208038a38, 0x7fb0146bfc68, 0xc208640000, 0xc208640020, 0xc2083097a0)
	/home/martin/code/go/src/github.com/lonelycode/tyk-analytics/Main.go:322 +0x11d
reflect.Value.call(0x816a80, 0x9d9de8, 0x13, 0x8d2c00, 0x4, 0xc208301210, 0x4, 0x4, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x816a80, 0x9d9de8, 0x13, 0xc208301210, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/gocraft/web.(*middlewareHandler).invoke(0xc2080e82d0, 0x8ce8a0, 0xc208038a38, 0x16, 0x7fb0146bfc68, 0xc208640000, 0xc208640020, 0xc2083097a0)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:133 +0x2d5
github.com/gocraft/web.func·002(0x7fb0146bfc68, 0xc208640000, 0xc208640020)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.func·004(0x7fb0146bfc68, 0xc208640000, 0xc208640020, 0xc2083097a0)
	/home/martin/code/go/src/github.com/gocraft/web/static_middleware.go:23 +0x64a
github.com/gocraft/web.(*middlewareHandler).invoke(0xc2080e80c0, 0x89dc80, 0xc208038a28, 0x16, 0x7fb0146bfc68, 0xc208640000, 0xc208640020, 0xc2083097a0)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:131 +0x71
github.com/gocraft/web.func·002(0x7fb0146bfc68, 0xc208640000, 0xc208640020)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.LoggerMiddleware(0x7fb0146bfc68, 0xc208640000, 0xc208640020, 0xc2083097a0)
	/home/martin/code/go/src/github.com/gocraft/web/logger_middleware.go:16 +0x78
github.com/gocraft/web.(*middlewareHandler).invoke(0xc2080e8090, 0x89dc80, 0xc208038a28, 0x16, 0x7fb0146bfc68, 0xc208640000, 0xc208640020, 0xc2083097a0)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:131 +0x71
github.com/gocraft/web.func·002(0x7fb0146bfc68, 0xc208640000, 0xc208640020)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:122 +0x1c8
github.com/gocraft/web.(*Router).ServeHTTP(0xc20807c160, 0x7fb0146bfc30, 0xc2082a9d60, 0xc2083104e0)
	/home/martin/code/go/src/github.com/gocraft/web/router_serve.go:48 +0x3cf
net/http.serverHandler.ServeHTTP(0xc20805c3c0, 0x7fb0146bfc30, 0xc2082a9d60, 0xc2083104e0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080623c0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

----------------------------------------------------------------------------------------------------------------------------------------

Now, dashboard config is pretty much stock: 

more tyk_analytics.conf 
{
    "listen_port": 3000,
    "tyk_api_config": {
        "Host": "http://10.0.0.74",
        "Port": "4000",
        "Secret": "352d20ee67be67f6340b4c0605b044b7"
    },
    "mongo_url": "mongodb://10.0.0.137/tyk_analytics",
    "page_size": 10,
    "admin_secret": "12345",
    "redis_port": 6379,
    "redis_host": "10.0.0.137",
    "redis_password": "",
    "force_api_defaults": true,
    "notify_on_change": true,
    "license_owner": "Your Name"
}

I can issue reload with auth on the gw node for example: 

telnet 10.0.0.74 4000
Trying 10.0.0.74...
Connected to 10.0.0.74.
Escape character is '^]'.
GET /tyk/reload/ HTTP/1.1
Host: localhost:5000
X-Tyk-Authorization: 352d20ee67be67f6340b4c0605b044b7
Cache-Control: no-cache

HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 19 May 2015 14:36:54 GMT
Content-Length: 26

{"status":"ok","error":""}

So I guess it can talk to the node. 

Btw I'm running gw nodes and host-manager in docker.

**Comment by lonelycode** [comment]
It looks like something is wrong with the User object or the schema, the dashboard is trying to validate the User object against the schema it has stored.

Two things worth checking:

1. Is there a `schemas/` folder in the tyk-dashboard folder and are there files in it?
2. What does the user record in your database look like? (Check the `tyk_analytics_users` collection in Mongo)

If there are no files in `schemas/` you may have a funky build, you'll need to replace them manually from one of the other tarballs.
More questions:

1. Which dashboard version are you running (latest is 0.9.4.4)? 
2. Did you build the docker container yourself or is it one of ours? 

Important to note that the master branch of our docker repo in Github is not used, only the version tags are. We recommend getting our pre-builts from docker hub since we validate those.

**Comment by samek** [comment]
Hi, 
1, No I don't have schemas folder  - but I've found it and put it into the docker.  *Which solved the problem* 
2. There's my user name inside. 
3. Dashboard is  0.9.3
4. I've build it myself obviously without schemas folder. 

Thanks. for the support.

**Comment by lonelycode** [comment]
Great to hear though I strongly recommend moving to 0.9.4.4 :-)
