### ISSUE TITLE
Question on API authentication middleware. 

### ISSUE THREAD

**Issue by raccoon42** [lonelycode/tyk#69]
I have two API upstream servers in which endpoints requires user authentication (token based ) via another upstream which provide authentication service ( not OAuth2)

So When a request comes I need to to validate the token in authentication server and then proxy the request to the actual upstream with an additional header with userid. ( userid is the response from authentication api server)

This is apart from the developer api key authentication , which means one API call should first check the developer API key( which is tyk do with token based auth) and then should follow the above flow.

What is the best way to do this? Should I create a middleware for this or is there any other simple option available?

**Comment by lonelycode** [comment]
Hi,

You will need to use a middleware for this, assuming that your authentication server has http access:

1. Request comes in with an API token + maybe the other auth data
2. API Token is checked by Tyk, if it is valid the request passes tbhrough the rest of the machinery, then before it leaves Tyk is passed to the middleware
3. The middleware calls your auth server, gets the user ID and adds it as a header to the outbound request along with any other data you may need to send upstream
4. The request proceeds onwards or is stalled by the middleware

We're looking into other methods for hooking up other auth systems, but their are very much still WIP :-/

**Comment by raccoon42** [comment]
Thanks for the reply. Is it possible to do http call from javascript middleware ? or I should write a middleware in go itself?

**Comment by lonelycode** [comment]
The JS middleware can handle http requests (it's a little tricky to test) but isn't as fast as golang, but you can just drop it into an existing install without recompiling.

If you want speed, write the middleware in golang - there's an example middleware file included in the source tree to see how the module is made.

Adding it to the chain is a matter of modifying the main.go file when it sets up the URL paths.

**Comment by raccoon42** [comment]
Thanks for the help. Will try with middleware.
