### ISSUE TITLE
Tyk as api gateway for microservices

### ISSUE THREAD

**Issue by bazani** [lonelycode/tyk#71]
Hi there! I'm searching for an api gateway for my new project. Can Tyk receive an request for one endpoint (/api/blog/post/123) and then consume multiples services (www.my.api/v1/post/123 and www.my.api/v1/comments?post-id=123) and wrap the response in one JSON object and only then answer that request for the endpoint?

**Comment by lonelycode** [comment]
Nope, it's a one for one proxy, though it does support batch requests to
group things like that for end users.

**Comment by bazani** [comment]
Thanks.
