### ISSUE TITLE
Updating listen_path does not stick

### ISSUE THREAD

**Issue by djcrabhat** [lonelycode/tyk#72]
Whether through the API or the dashboard interface, we cannot update the listen path.  The API returns an OK code, saying it worked, but listen_path stubbornly stays to the default value of api_id.

Also, when trying to POST a new API and explicitly setting listen_path, it always goes to api_id

This is happening in 1.7.1

**Comment by lonelycode** [comment]
set `use_api_defaults` to false in your tyk_analytics.conf

Tyk has some preset modes to enforce certain safe behaviours. Setting this option to false will stop Tyk from trying to build the listen path for you.
