### ISSUE TITLE
Gateway API Doesn't allow listen path to be renamed

### ISSUE THREAD

**Issue by saaqibz** [lonelycode/tyk#75]
Using latest docker pull of tyk_gateway as of today (7/3/2015).

I am trying to rename the listen path from '/a39e0fa55f6e445e58355bde9a9377fa/' to '/restricted/' using the tyk dashboard.

Reproduce:

1. Create an api
2. Go to the api edit screen
3. rename listen path for /{api_id}/  to /restricted/
4. save
5. Leave and return to the page to see that the path is unchanged.

it was working before but now it does not work. If it works the first time, you may need to rename it back to the api_id and try naming it restricted again.

**Comment by lonelycode** [comment]
You will need to set `use_api_defaults` to `false` in the `tyk_analytics.conf` file for the listen path to not be managed by the dashboard.

Let me know if this works, it should...
    _____________________________

**Comment by saaqibz** [comment]
Hi Martin,

I'm using the tyk dropbox application so it's not really all that straightforward to change the tyk_analytics file. I found a workaround where I'll just use the listen_path, but I'll investigate later to see if I can make the change that you mentioned.

What I was really hoping is that the listen_path field in the dashboard would be editable as the text field suggests that you can update it and click update. This feature used to work before but for some reason it stopped working after the most recent update. When I have time to play around a bit I'll get back to you about the adjustment to the tyk analytics conf file.

**Comment by lonelycode** [comment]
If you are uing the docker version, it is incredibly simple to change the option using standard docker command line flags. Use the -v option to mount your own tyk_analytics file over the one that is bundled (see [this section](https://docs.docker.com/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume) in the docker docs).

The config file will be located under `/opt/tyk-dashboard/tyk_analytics.conf` in the container, and it is the vanilla one that ships with the tarball (see our releases page on GH), so you can download a copy and use that.

We've made this a little stricter in the latest version as the dashboard by default will enforce an API ID to be used so as to prevent users from entering conflicting paths by accident (or maliciously), using the REST API.

I've just looked into it a bit more, and there is one side-effect that you may encounter when you change the option - the force defaults option also sets the "strip_listen_path" setting in the API definition to `true`, this prevents your listen path from being transmitted along to the upstream API. 

This option can't be set in the dashboard at the moment, so you would need to make the change using the REST API instead :-/

**Comment by lonelycode** [comment]
I've pushed an update - Dashboard 0.9.5.2 to our releases page and our docker repository that addresses the problem. LIsten path should now be editable without resorting to switching off API default safety.

You may need to wait a while for the docker hub container to build and update though. But you should be able to just docker pull -u to update it.

**Comment by saaqibz** [comment]
You're the best Martin. :) Thanks a ton!

On Sun, Jul 5, 2015 at 12:59 PM, Martin Buhr <notifications@github.com>
wrote:

> I've pushed an update - Dashboard 0.9.5.2 to our releases page and our
> docker repository that addresses the problem. LIsten path should now be
> editable without resorting to switching off API default safety.
>
> You may need to wait a while for the docker hub container to build and
> update though. But you should be able to just docker pull -u to update it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lonelycode/tyk/issues/75#issuecomment-118644306>.
>



-- 
S. Alexander Zaman
-Sent from my Droid

**Comment by lonelycode** [comment]
Unfortunately docker hub seems to be having an issue so the image isn't pushing. *sigh*. Might take a while...

**Comment by lonelycode** [comment]
Aaaaaand the docker build pushed successfully. Done.
