### ISSUE TITLE
tyk dashboard - freebsd binary

### ISSUE THREAD

**Issue by krzysztofantczak** [lonelycode/tyk#78]
Hi,

Is it possible to get freebsd version of tyk dashboard (both 386 and amd64 would be awesome)?

**Comment by lonelycode** [comment]
Don't see why not, will modify our build script to include these, though it will most likely only be the tarballs...

**Comment by lonelycode** [comment]
Here's a cut from dev - should be pretty stable, there have been very few changes to this build for now:

https://www.dropbox.com/sh/e2ev1yqjhcv7nyi/AAAZbUSSxOLAn8wHFNhMTC8Ha?dl=0

Want to give it a test to see if it behaves itself?

**Comment by krzysztofantczak** [comment]
Well, since i'm just starting with tyk, i can only tell if it works or not - can't give much details yet - i think. Thanks for binaries! ;-)

**Comment by lonelycode** [comment]
We do dashboard BSD builds all the time now as standard.
