### ISSUE TITLE
Integrate OpenId protocol into Tyk

### ISSUE THREAD

**Issue by r-kozak** [lonelycode/tyk#79]
Hi!
How I can integrate OpenId connect protocol into Tyk?

**Comment by lonelycode** [comment]
Not much coverage on OpenId in golang land - there's this library: https://github.com/ekozan/OpenID-Connect But it doesn't seem to have many tests (or any kind of validation). 

There's another lib but it seems to be very WIP, so will steer clear of that. 

To implement this we'd probably need some kind of layer on top of our OAuth 2.0 server. Would even need to test if it's compatible. TBH I know very little abut OpenID.

I'm a little concerned about how many versions there are of this protocol...

If there's enough demand around this feature will be happy to add to roadmap.

Obviously will be happy to help anyone else who wants to take on the challenge and add support in themselves ;-)

**Comment by r-kozak** [comment]
Thank you for answer!
