### ISSUE TITLE
Custom portal templates not registering?

### ISSUE THREAD

**Issue by toringe** [lonelycode/tyk#83]
In `portal/templates/myindex.html` I try to register a new template for my customized portal: 
```
{{ define "MyIndexPage" }} 
{{ template "header" .}} 
<body>
...
```
And in `Dashboard > Portal Management > Pages > Homepage` I set
`Template name code` to  `MyIndexPage` and restart the `tyk-analytics` process. (I've checked "Make Homepage" in my `Homepage` page setting)

But changes in `myindex.html` are not displayed, however if I change `index.html` instead, the changes are properly displayed on my portal webpage.

Is it something I have forgotten, or do I need to register the templates in another fashion?

**Comment by lonelycode** [comment]
Templates are loaded into memory when the aplpication starts, you will need to restart the process for the template to be registered.

**Comment by toringe** [comment]
I have restarted the `tyk-analytics` process, but it still uses the indexPage template defined in index.html.

**Comment by lonelycode** [comment]
Ah, wait a second - the index page is s special case :-/ The name of the template is hard coded to "indexPage"

You will need to modify indexPage directly or name your new template indexPage nand rename the other one.
