### ISSUE TITLE
Tyk is not raising errors when speaking to a read only redis slave

### ISSUE THREAD

**Issue by 4lyn** [lonelycode/tyk#91]
Hi,

When there is a change in the redis Cluster and Tyk is still talking to a slave, it is still answering success codes although it logs errors in storing the new created key :

When a run the following command

$ curl -X PUT http://localhost:8080/tyk/keys/key_value  --header "x-tyk-authorization: TYK_TOKEN"  --header "Content-Type:application/json"  --data '{
"allowance": 1000,
"rate": 1000,
"per": 1,
"expires": 0,
"quota_max": -1,
"access_rights": {
"1": {}
},
"org_id": ""
}'

I get this response as it would be working normally :
{"key":"key_value","status":"ok","action":"modified"}

But the key is not listed in the response of this command :
$ curl -X GET http://localhost:8080/tyk/keys --header "x-tyk-authorization: TYK_TOKEN"

Here is what I get in the tyk.log :
time="2015-08-24T12:02:58+02:00" level=warning msg="Tracked quota reset for key: key_value"
time="2015-08-24T12:02:58+02:00" level=info msg="New key added or updated." key="key_value"
time="2015-08-24T12:02:58+02:00" level=error msg="Error trying to set value:"
time="2015-08-24T12:02:58+02:00" level=error msg="READONLY You can't write against a read only slave."

**Comment by lonelycode** [comment]
This is fixed in master branch now. API will return error when create key and writes fail.

**Comment by 4lyn** [comment]
Great

Thanks

2015-09-02 11:00 GMT+02:00 Martin Buhr <notifications@github.com>:
