### ISSUE TITLE
Better quickstart support

### ISSUE THREAD

**Issue by yoanisgil** [lonelycode/tyk#95]
Hi there,

In light of issues reported here:

https://gist.github.com/lonelycode/4f645c4733faaa74d8fd

I have created a github project to help with getting Tyk up and running in a more repeatable and easier way:

https://github.com/yoanisgil/tyk_quickstart

But maybe it's a better idea to have this included within the project itself (specially considering that the Gist is linked in the official documentation and people have been having issues with that ...).

Bests,

Yoanis.

**Comment by lonelycode** [comment]
Amazing - I'll update the docs with a link to this from the docker quickstart, much simpler, it's a great idea. Thank you! :-)

**Comment by yoanisgil** [comment]
Great. It will be nice if we could support at least the two latest versions. Will look into it. I am not a big fan of using ```latest``` so I will update and make that more explicit.

**Comment by lonelycode** [comment]
This is now in the main docs here as an alternative quickstart: https://tyk.io/v1.8/setup/docker/
