### ISSUE TITLE
API Catalogue not displaying swagger documentation

### ISSUE THREAD

**Issue by toringe** [lonelycode/tyk#97]
When using 0.9.6 dashboard on an offline server the "view documentation" page do not display the uploaded swagger documentation. If I add "raw" to the uri (e.g. `/portal/apis/<api-id>/documentation/raw`) I do get the swagger.json file I pasted on the dashboard.

Doing the exact same thing on an online server with the same software version, and it works. 

Is there any online deps for showing this kind of documentation?

**Comment by lonelycode** [comment]
Yes there is, for online portals it uses the latest version of the swagger
JS I believe.
it will also use an exgternal validator too.

However, the portal templates are changeable, just look at the
portals/swagger.html file to change the deps to something local.

**Comment by lonelycode** [comment]
Actually, it's probably JQUery missing, in the `/portal/tempaltes/scripts.html` file there's a reference to the CDN version:

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

Replace this with a local version and it should work :-)

**Comment by toringe** [comment]
Yes, that was it! Added jquery to portal-assets/js and updated scripts.html. Works just fine. Thanks!
