### ISSUE TITLE
Issue navigating the developer portal

### ISSUE THREAD

**Issue by JnMik** [lonelycode/tyk#99]
When I access the portal through the "Your developer portal" link in the dashboard,
I have an URL with an ID in it ( http://screencast.com/t/6jjTB8t2om )

But once I get into the portal, all the internal links doesn't have that ID so I must 
build all the urls by hand lol

http://screencast.com/t/vV63FCQFU

Also, the URL on the "Your developer portal" link is using the current IP for the host.
The thing is, that IP is the one from my Docker Server, running in a vm.
That IP is in another subnet than my real PC, so I cannot access it.

Maybe the URL should be built with the actual hostname ? 
http://screencast.com/t/meMaQwhAVT

Thx !

**Comment by lonelycode** [comment]
Yeah that will happen if you haven't set up a host name
This is a new thing (not documented yet) - you need to set the hostname field in the tyk_analytics.conf file to your desired host name to override that. This literally came out yesterday and the docs haven't caught up yet :-)
Tyk tries to be clever with identifying it's hostname and IP for the gateway and portal to get things to work, but for it to work as needed (like our cloud setup) you need to set the hostname field and get the host manager running (https://tyk.io/v1.8/host-manager/). There's only so much we can do to detect environments...
Also take a look at this: https://tyk.io/v1.8/tyk-routing/
The portal is heavily dependent on URL rewriting, you can obviously change that my manually editing the templates, but using the host manager and the provided templates sorts all this out quite quickly.

**Comment by lonelycode** [comment]
What I'll do is improve the docs around this - the portal URL routing really messes with self hosted users.
Watch this space :-)

**Comment by JnMik** [comment]
Awesome, I'll check this out :)
Have a good weekend !
